In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Recommend.csv')
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [3]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0]
n_movies = df.movie_id.unique().shape[0]
train_data, test_data = train_test_split(df, test_size = 0.25)

In [4]:
print(n_users, n_movies)

943 1682


In [5]:
train_data_matrix = np.zeros((n_users, n_movies))

In [6]:
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis = 1)[:, np.newaxis]
ratings_diff = (train_data_matrix - mean_user_rating)
user_pred = mean_user_rating + user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).sum(axis = 1)]).T
user_pred

array([[ 1.5885245 ,  0.57824848,  0.47699279, ...,  0.29692741,
         0.29437144,  0.29669056],
       [ 1.33366107,  0.29498138,  0.15221293, ..., -0.05902405,
        -0.06090781, -0.05752773],
       [ 1.35201801,  0.24994036,  0.11529836, ..., -0.10456128,
        -0.10603072, -0.1025745 ],
       ...,
       [ 1.20349568,  0.21579881,  0.08240893, ..., -0.1200998 ,
        -0.12238734, -0.11935908],
       [ 1.37269644,  0.31441786,  0.20523801, ..., -0.00358017,
        -0.00570734, -0.00247452],
       [ 1.40723849,  0.35744881,  0.25977223, ...,  0.07451785,
         0.07206228,  0.07467747]])